create or replace view fth_person as select * from person limit 2000000;
create or replace view fth_drug_era as select drug_era.* from drug_era join fth_person on drug_era.person_id = fth_person.person_id;
create or replace view fth_condition_era as select condition_era.* from condition_era join fth_person on condition_era.person_id = fth_person.person_id;
create or replace view fth_observation_period as select observation_period.* from observation_period join fth_person on observation_period.person_id = fth_person.person_id;
